// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway.proto

#ifndef PROTOBUF_INCLUDED_gateway_2eproto
#define PROTOBUF_INCLUDED_gateway_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_gateway_2eproto 

namespace protobuf_gateway_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_gateway_2eproto
namespace bite_im {
class ClientAuthenticationReq;
class ClientAuthenticationReqDefaultTypeInternal;
extern ClientAuthenticationReqDefaultTypeInternal _ClientAuthenticationReq_default_instance_;
}  // namespace bite_im
namespace google {
namespace protobuf {
template<> ::bite_im::ClientAuthenticationReq* Arena::CreateMaybeMessage<::bite_im::ClientAuthenticationReq>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace bite_im {

// ===================================================================

class ClientAuthenticationReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:bite_im.ClientAuthenticationReq) */ {
 public:
  ClientAuthenticationReq();
  virtual ~ClientAuthenticationReq();

  ClientAuthenticationReq(const ClientAuthenticationReq& from);

  inline ClientAuthenticationReq& operator=(const ClientAuthenticationReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ClientAuthenticationReq(ClientAuthenticationReq&& from) noexcept
    : ClientAuthenticationReq() {
    *this = ::std::move(from);
  }

  inline ClientAuthenticationReq& operator=(ClientAuthenticationReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientAuthenticationReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ClientAuthenticationReq* internal_default_instance() {
    return reinterpret_cast<const ClientAuthenticationReq*>(
               &_ClientAuthenticationReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ClientAuthenticationReq* other);
  friend void swap(ClientAuthenticationReq& a, ClientAuthenticationReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ClientAuthenticationReq* New() const final {
    return CreateMaybeMessage<ClientAuthenticationReq>(NULL);
  }

  ClientAuthenticationReq* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ClientAuthenticationReq>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ClientAuthenticationReq& from);
  void MergeFrom(const ClientAuthenticationReq& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientAuthenticationReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string request_id = 1;
  void clear_request_id();
  static const int kRequestIdFieldNumber = 1;
  const ::std::string& request_id() const;
  void set_request_id(const ::std::string& value);
  #if LANG_CXX11
  void set_request_id(::std::string&& value);
  #endif
  void set_request_id(const char* value);
  void set_request_id(const char* value, size_t size);
  ::std::string* mutable_request_id();
  ::std::string* release_request_id();
  void set_allocated_request_id(::std::string* request_id);

  // string session_id = 2;
  void clear_session_id();
  static const int kSessionIdFieldNumber = 2;
  const ::std::string& session_id() const;
  void set_session_id(const ::std::string& value);
  #if LANG_CXX11
  void set_session_id(::std::string&& value);
  #endif
  void set_session_id(const char* value);
  void set_session_id(const char* value, size_t size);
  ::std::string* mutable_session_id();
  ::std::string* release_session_id();
  void set_allocated_session_id(::std::string* session_id);

  // @@protoc_insertion_point(class_scope:bite_im.ClientAuthenticationReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr request_id_;
  ::google::protobuf::internal::ArenaStringPtr session_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_gateway_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ClientAuthenticationReq

// string request_id = 1;
inline void ClientAuthenticationReq::clear_request_id() {
  request_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ClientAuthenticationReq::request_id() const {
  // @@protoc_insertion_point(field_get:bite_im.ClientAuthenticationReq.request_id)
  return request_id_.GetNoArena();
}
inline void ClientAuthenticationReq::set_request_id(const ::std::string& value) {
  
  request_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bite_im.ClientAuthenticationReq.request_id)
}
#if LANG_CXX11
inline void ClientAuthenticationReq::set_request_id(::std::string&& value) {
  
  request_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bite_im.ClientAuthenticationReq.request_id)
}
#endif
inline void ClientAuthenticationReq::set_request_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  request_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bite_im.ClientAuthenticationReq.request_id)
}
inline void ClientAuthenticationReq::set_request_id(const char* value, size_t size) {
  
  request_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bite_im.ClientAuthenticationReq.request_id)
}
inline ::std::string* ClientAuthenticationReq::mutable_request_id() {
  
  // @@protoc_insertion_point(field_mutable:bite_im.ClientAuthenticationReq.request_id)
  return request_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ClientAuthenticationReq::release_request_id() {
  // @@protoc_insertion_point(field_release:bite_im.ClientAuthenticationReq.request_id)
  
  return request_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ClientAuthenticationReq::set_allocated_request_id(::std::string* request_id) {
  if (request_id != NULL) {
    
  } else {
    
  }
  request_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), request_id);
  // @@protoc_insertion_point(field_set_allocated:bite_im.ClientAuthenticationReq.request_id)
}

// string session_id = 2;
inline void ClientAuthenticationReq::clear_session_id() {
  session_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ClientAuthenticationReq::session_id() const {
  // @@protoc_insertion_point(field_get:bite_im.ClientAuthenticationReq.session_id)
  return session_id_.GetNoArena();
}
inline void ClientAuthenticationReq::set_session_id(const ::std::string& value) {
  
  session_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bite_im.ClientAuthenticationReq.session_id)
}
#if LANG_CXX11
inline void ClientAuthenticationReq::set_session_id(::std::string&& value) {
  
  session_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bite_im.ClientAuthenticationReq.session_id)
}
#endif
inline void ClientAuthenticationReq::set_session_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  session_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bite_im.ClientAuthenticationReq.session_id)
}
inline void ClientAuthenticationReq::set_session_id(const char* value, size_t size) {
  
  session_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bite_im.ClientAuthenticationReq.session_id)
}
inline ::std::string* ClientAuthenticationReq::mutable_session_id() {
  
  // @@protoc_insertion_point(field_mutable:bite_im.ClientAuthenticationReq.session_id)
  return session_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ClientAuthenticationReq::release_session_id() {
  // @@protoc_insertion_point(field_release:bite_im.ClientAuthenticationReq.session_id)
  
  return session_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ClientAuthenticationReq::set_allocated_session_id(::std::string* session_id) {
  if (session_id != NULL) {
    
  } else {
    
  }
  session_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), session_id);
  // @@protoc_insertion_point(field_set_allocated:bite_im.ClientAuthenticationReq.session_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace bite_im

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_gateway_2eproto
